---
# Master SSH tunnel configuration
default_profile: example-profile

profiles:
  example-profile:
    jump_host: 1.2.3.4         # Replace with your jump server IP
    jump_user: youruser        # Replace with your SSH username
    identity_file: ~/.ssh/id_ed25519
    use_autossh: false
    tunnels:
      - name: example-tunnel-1
        local_port: 22222
        target_ip: 10.0.0.1
        target_port: 22

      - name: example-tunnel-2
        local_port: 33333
        target_ip: 10.0.0.2
        target_port: 3389

  another-profile:
    jump_host: 5.6.7.8
    jump_user: anotheruser
    identity_file: ~/.ssh/id_rsa
    use_autossh: true
    tunnels:
      - name: another-tunnel
        local_port: 44444
        target_ip: 10.1.1.1
        target_port: 8080
