tunnels:
  - name: proxmox
    local_port: 8006
    target_ip: 192.168.227.7
    target_port: 8006
  - name: maas
    local_port: 5240
    target_ip: 192.168.227.3
    target_port: 5240
  - name: win_rdp
    local_port: 13389
    target_ip: 192.168.227.53
    target_port: 3389
  - name: win_winrm
    local_port: 15986
    target_ip: 192.168.227.53
    target_port: 5986